
public class main {
    public static <bukuSejarah> void main(String[] args) {
        buku teknologi1 = new buku("Homo Deus", "786026577337", "Yuval Noah Harari", "448");
        buku teknologi2 = new buku("The Shallows", "9780393357820", "Nicholas Carr", "280");
        buku teknologi3 = new buku("The Great Shifting", "9786020387604", "Rhenald kasali", "584");
        buku teknologi4 = new buku("Everybody Lies", "9786020612096", "Seth Stephens", "336");
        buku teknologi5 = new buku("The Death of Expertise", "9780190865979", "Tom Nichols", "280");
        System.out.println("===================================================");
        System.out.println("Daftar Buku Teknologi = ");
        System.out.println("buku 1 = ");
        teknologi1.show();
        System.out.println("buku 2 = ");
        teknologi2.show();
        System.out.println("buku 3 = ");
        teknologi3.show();
        System.out.println("buku 4 = ");
        teknologi4.show();
        System.out.println("buku 5 = ");
        teknologi5.show();

        buku filsafat1 = new buku("Passions of the Soul", "9786236166826", "Renee Descartes", "274");
        buku filsafat2 = new buku("Madilog", "9786025792403", "Tan Malaka", "560");
        buku filsafat3 = new buku("Beyond Good and Evil", "9781507764596", "Fredrich Nietszche", "272");
        buku filsafat4 = new buku("A History of God", "9780345384560", "Karen Amstrong", "460");
        buku filsafat5 = new buku("Loving Wounded Soul", "9786020633718", "Regis Machdy", "324");
        System.out.println("===================================================");
        System.out.println("Daftar Buku Filsafat = ");
        System.out.println("buku 1 = ");
        filsafat1.show();
        System.out.println("buku 2 = ");
        filsafat2.show();
        System.out.println("buku 3 = ");
        filsafat3.show();
        System.out.println("buku 4 = ");
        filsafat4.show();
        System.out.println("buku 5 = ");
        filsafat5.show();

        buku Sejarah1 = new buku("Sejarah Dunia yang Didembunyikan","9786029193671","Jonathan Black","636");
        buku Sejarah2 = new buku("Sejarah Teh","9786230013201","Laura Martin","226");
        buku Sejarah3 = new buku("A History of God","9780345384560","Karen Amstrong","460");
        buku Sejarah4 = new buku("Homo Deus","786026577337","Yuval Noah Harari","448");
        buku Sejarah5 = new buku("Hiroshima","9780593080696","John Hersey","166");
        System.out.println("===================================================");
        System.out.println("Daftar Buku Sejarah = ");
        System.out.println("buku 1  ");
        Sejarah1.show();
        System.out.println("buku 2  ");
        Sejarah2.show();
        System.out.println("buku 3  ");
        Sejarah3.show();
        System.out.println("buku 4  ");
        Sejarah4.show();
        System.out.println("buku 5  ");
        Sejarah5.show();

        buku Agama1 = new buku("No God but god","9780099564324","Reza Aslam","320");
        buku Agama2 = new buku("The Story of Qur'an","9780470673492","Ingrid Mattson","312");
        buku Agama3 = new buku("Generation M","9786022912606","Shelina Janmohamed","276");
        buku Agama4 = new buku("The Great Theft: Wrestling Islam from The Extremes","9787493340694","Khaled Abou El Fadl","277");
        buku Agama5 = new buku("Muhammad: A Prophet for Our Time","9780739482636","Karen Armstrong","256");
        System.out.println("===================================================");
        System.out.println("Daftar Buku Agama = ");
        System.out.println("buku 1  ");
        Agama1.show();
        System.out.println("buku 2  ");
        Agama2.show();
        System.out.println("buku 3  ");
        Agama3.show();
        System.out.println("buku 4  ");
        Agama4.show();
        System.out.println("buku 5  ");
        Agama5.show();

        buku Psikologi1 = new buku("Atomic habits","9786020633176","James Clear","320");
        buku Psikologi2 = new buku("The Art of Choosing","9780446504119","Sheena Lyengar","329");
        buku Psikologi3 = new buku("The Emotional Brain","9780684836591","Joseph LeDoux","384");
        buku Psikologi4 = new buku("The 5AM Club","9781443460712","Robin Sharma","336");
        buku Psikologi5 = new buku("The Power Of Habit","9780812981605","Charles Duhigg","370");
        System.out.println("===================================================");
        System.out.println("Daftar Buku Psikologi = ");
        System.out.println("buku 1  ");
        Psikologi1.show();
        System.out.println("buku 2 ");
        Psikologi2.show();
        System.out.println("buku 3  ");
        Psikologi3.show();
        System.out.println("buku 4  ");
        Psikologi4.show();
        System.out.println("buku 5  ");
        Psikologi5.show();

        buku politik1 = new buku("Politik Identitas Kesaktian dan Kekuatan","9789797720254","Otto Sukatno","124");
        buku politik2 = new buku("The Republic","9787513346394","Plato","342");
        buku politik3 = new buku("Politik Kuasa Media","9799900964","Noam Chomsky","250");
        buku politik4 = new buku("Politik dan Kebebasan","9786236421208","Tom Palmer","200");
        buku politik5 = new buku("Politik, Partai Polik, dan Perempuan","9789791260107","Imron Wasi","104");
        System.out.println("===================================================");
        System.out.println("Daftar Buku Politik = ");
        System.out.println("buku 1  ");
        politik1.show();
        System.out.println("buku 2  ");
        politik2.show();
        System.out.println("buku 3  ");
        politik3.show();
        System.out.println("buku 4  ");
        politik4.show();
        System.out.println("buku 5  ");
        politik5.show();

        buku fiksi1 = new buku("The Martian","9780804139021","Andy Weir","369");
        buku fiksi2 = new buku("The Christmas Pig","9787513340694","JK Rowling","320");
        buku fiksi3 = new buku("Earth","9786020627526","Tere Liye","551");
        buku fiksi4 = new buku("The Sea Speak His Name","9789814882316","Leila Chudori","308");
        buku fiksi5 = new buku("Max Havelaar","9786021637456","Multatuli","396");
        System.out.println("===================================================");
        System.out.println("Daftar Buku Fiksi = ");
        System.out.println("buku 1 ");
        fiksi1.show();
        System.out.println("buku 2  ");
        fiksi2.show();
        System.out.println("buku 3  ");
        fiksi3.show();
        System.out.println("buku 4  ");
        fiksi4.show();
        System.out.println("buku 5  ");
        fiksi5.show();

    }
}
